
name: 'email'

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: self-hosted
    steps:  
      - name: 'release_note'
        run: bash /home/roborock_rc/Cinderella/email.bash
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.exmail.qq.com
          server_port: 465
          username: "guomingli@roborock.com"
          password: "Guo@0521"
          subject: test
          body: file:/home/roborock_rc/Cinderella/email.txt
          to: 1260306690@qq.com
          from: GitHub Actions
          content_type: text/html
