name: 'HF0.1-email'

on:
  workflow_dispatch:

jobs:
  bot:
    runs-on: auto_build
    steps:  
      - name: 'release_note'
        run: bash /home/roborock/Cinderella_HF0_1/release_note.sh
      - name: 'write email'
        run: bash /home/roborock/Cinderella_HF0_1/email.bash
      - name: 'get email subject'
        run: echo "DATE=$(sed -n "1p" /home/roborock/Cinderella_HF0_1/email_subject.txt)" >>  $GITHUB_ENV
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.exmail.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_NAME }}
          password: ${{ secrets.EMAIL_PASSWD }}
          subject: ${{env.DATE}}
          body:  file:///home/roborock/Cinderella_HF0_1/email.txt
          to: ${{ secrets.EMAIL_TO }}
          cc: ${{ secrets.EMAIL_CC }}
          from: 商用DEB打包机器人
          content_type: text/html
