name: HF1.0_CI_BUILD
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: build
        run: bash /home/roborock_rc/Cinderella/cinderella_build.bash
      - name: move
        run: bash /home/roborock_rc/Cinderella/move_deb.bash
