name: HF1.1_INDOOR_CI_BUILD
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: auto_build
    steps:
      - name: build
        run: bash /home/roborock/Cinderella_Indoor_HF1_1/cinderella_build.bash
      - name: 'Send build error mail'
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.exmail.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_NAME }}
          password: ${{ secrets.EMAIL_PASSWD }}
          subject: indoor_HF1.1编译错误
          body:  indoor_HF1.1请检查编译
          to: ${{ secrets.EMAIL_TO_DEVELOPER }}
          from: 商用DEB打包机器人
          content_type: text/html
        
  move_to_share:
    name: move_to_share
    runs-on: auto_build
    needs: build
    steps:
      - name: move
        run: bash /home/roborock/Cinderella_Indoor_HF1_1/move_deb.bash
      - name: 'Send copy error mail'
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.exmail.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_NAME }}
          password: ${{ secrets.EMAIL_PASSWD }}
          subject: indoor_HF1.1拷贝错误
          body:  indoor_HF1.1请检查拷贝
          to: ${{ secrets.EMAIL_TO_DEVELOPER }}
          from: 商用DEB打包机器人
          content_type: text/html
        
        
  send_email:
    runs-on: auto_build
    needs: [build, move_to_share]
    steps:  
      - name: 'release_note'
        run: bash /home/roborock/Cinderella_Indoor_HF1_1/release_note.sh
      - name: 'write email'
        run: bash /home/roborock/Cinderella_Indoor_HF1_1/email.bash
      - name: 'get email subject'
        run: echo "DATE=$(sed -n "1p" /home/roborock/Cinderella_Indoor_HF1_1/email_subject.txt)" >>  $GITHUB_ENV
      - name: 'Send email'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.exmail.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_NAME }}
          password: ${{ secrets.EMAIL_PASSWD }}
          subject: ${{env.DATE}}
          body:  file:///home/roborock/Cinderella_Indoor_HF1_1/email.txt
          to: ${{ secrets.EMAIL_TO }}
          cc: ${{ secrets.EMAIL_CC }}
          from: 商用DEB打包机器人
          content_type: text/html
